### ISSUE TITLE
delete and sort

### ISSUE THREAD

**Issue by ammmmmmmmmmm** [ulan17/TimeTable#10]
How to delete timetable slot that we add and sort automatic follow time

**Comment by ulan17** [comment]
Hi, @ammmmmmmmmmm. Just, click long item of list, which you want to delete. And, you will see toolbar menu with delete and edit function.

**Comment by ammmmmmmmmmm** [comment]
Hi,@ulan17..tq..nice apps btw..better if can sort automatically follow time we set..

**Comment by ulan17** [comment]
@ammmmmmmmmmm Thanks. I will consider about it. And as soon as possible, I will add this feature.

**Comment by ulan17** [comment]
Hey @ammmmmmmmmmm, I added auto sort. You can check it. By the way, thanks for your idea.  👍
