### ISSUE TITLE
Days Translate

### ISSUE THREAD

**Issue by dorular** [ulan17/TimeTable#12]
Hi ulan, i wanna ask you something.

When i translate the days to my language i can't see my records. when i turned day names originally, all records come back. I think its about db values. How can i fix that issue.

Btw Thanks for sharing this beautiful app.

**Comment by ulan17** [comment]
Hi @ibrahimib. You are right it's about database values. I will fix it.

By the way, please fork repository, if you want to change something.

**Comment by ulan17** [comment]
Hi @ibrahimib. I have fixed this issue. Now, please try it out again.

**Comment by dorular** [comment]
well done @ulan17 it works perfectly. Thanks a lot.
