### ISSUE TITLE
Firebase Integration

### ISSUE THREAD

**Issue by pharshdev** [ulan17/TimeTable#14]
Firstly, this app is a great base for me to build upon. Good work. It caters all my needs. I was thinking of integrating the app with Firebase since we have a very dynamic schedule with lot of class shuffling at odd times. So one person (Class Rep) would update the table, Assignments etc and everyone else would receive the update instead of everyone doing the same. Did you try integrating it with Firebase? Also would you advice shifting the complete local DB to Cloud Firestore?

**Comment by ulan17** [comment]
@rash191 Hi. Good idea. I've been considering shifting to Firebase.

-Did you try integrating it with Firebase?
-No, I didn't. But, I tried it with another app.
-Also would you advice shifting the complete local DB to Cloud Firestore?
-I think I can advice, also Firebase gives a lot of convenient things.

**Comment by pharshdev** [comment]
I'm working on it. Will update.

**Comment by pharshdev** [comment]
Ok so for an update. This weekend was fun. Drawing cues from your app, I started working on a fresh project. I was able to implement the basic functionality.  Checkout my repo: https://github.com/rash191/NextClass
