### ISSUE TITLE
Logo Design for TimeTable

### ISSUE THREAD

**Issue by zularizal** [ulan17/TimeTable#7]
Hi @ulan17 , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by ulan17** [comment]
@zularizal Hi, great idea. I was thinking about it. I'd be very grateful if you could help me. Also, you can reach out to me by [telegram](https://t.me/ulan17).

**Comment by zularizal** [comment]
Okay. Give me time to make it. I will upload a new logo proposal on your telegram.

**Comment by zularizal** [comment]
Hi @ulan17 , I have uploaded the logo and icon to the drive.

https://drive.google.com/open?id=1tscE6uGI2q_1c4L-BIRaDTwKEo4s030r

And also I have sent pr for you. #9

**Comment by ulan17** [comment]
@zularizal, thank you a lot. I've merger your PR 👍
